In [1]:
import pandas as pd

In [2]:
#machine = 'centos-7'
machine = 'centos-7-02'

cov_df = pd.read_csv('../01-uncon_v_con_shock_MR_ROI24_with_covariates/uncon_v_con_shock_MR_ROI24final_with_covariates.txt',sep='\t')
df = pd.read_csv(machine+'/uncon_v_con_lInsula_shock.txt',sep='\t')
print('cov shape:', cov_df.shape)
print('df shape:', df.shape)
cov_df.head()

cov shape: (1464, 8)
df shape: (57401, 4)

,Subj,ROI,Y,TRAITmean,TRAITdiff,STATEmean,STATEdiff,BPdiff_stdz
0,P00,L Amygdala (BLBM),-0.0841,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
1,P00,R Amygdala (BLBM),0.1305,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
2,P00,L Amygdala (CeME),0.1827,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
3,P00,R Amygdala (CeME),0.2318,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
4,P00,L aMCC,1.3089,-1.003,-0.0406,-1.2307,-0.1812,-0.8664

In [3]:
cov_df = cov_df.drop(['ROI','Y'],axis=1).drop_duplicates().reset_index(drop=True)

In [4]:
cov_df.head()

  Subj  TRAITmean  TRAITdiff  STATEmean  STATEdiff  BPdiff_stdz
0  P00    -1.0030    -0.0406    -1.2307    -0.1812      -0.8664
1  P01    -0.4359     3.1472    -0.4379     0.4163       0.3736
2  P02     0.1942     0.3136    -0.5172     0.3167      -0.3028
3  P03    -1.5702     1.0220    -1.6270    -0.0816       0.3360
4  P04    -0.2469    -0.0406    -0.2794     0.6155      -0.7913

In [5]:
df.head()

                        ROI Subj                           VOX         Y
0  L Anterior dorsal insula  P00  L Anterior dorsal insula 000  0.197452
1  L Anterior dorsal insula  P00  L Anterior dorsal insula 001 -0.355381
2  L Anterior dorsal insula  P00  L Anterior dorsal insula 002  0.043994
3  L Anterior dorsal insula  P00  L Anterior dorsal insula 003  0.232958
4  L Anterior dorsal insula  P00  L Anterior dorsal insula 004 -0.015846

In [6]:
df = df.merge(right=cov_df)
df.head()

,ROI,Subj,VOX,Y,TRAITmean,TRAITdiff,STATEmean,STATEdiff,BPdiff_stdz
0,L Anterior dorsal insula,P00,L Anterior dorsal insula 000,0.197452,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
1,L Anterior dorsal insula,P00,L Anterior dorsal insula 001,-0.355381,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
2,L Anterior dorsal insula,P00,L Anterior dorsal insula 002,0.043994,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
3,L Anterior dorsal insula,P00,L Anterior dorsal insula 003,0.232958,-1.003,-0.0406,-1.2307,-0.1812,-0.8664
4,L Anterior dorsal insula,P00,L Anterior dorsal insula 004,-0.015846,-1.003,-0.0406,-1.2307,-0.1812,-0.8664

In [7]:
df.to_csv(machine+'/uncon_v_con_lInsula_shock.txt',sep='\t',index=False,float_format='%.4f')